; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
IdleStk:
	TIMES	512 db 0
YKRdyTCBList:
	TIMES	2 db 0
YKemptyTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	96 db 0
YKcurrTask:
	TIMES	2 db 0
YKReadyNextTask:
	TIMES	2 db 0
running:
	TIMES	2 db 0
depth:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
CurrPriority:
	TIMES	2 db 0
NextPriority:
	TIMES	2 db 0
FirstDispatcherFlag:
	TIMES	2 db 0
